# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee014d47c741d7fea0e32e53d5e3e2b7ddf3219c39128b8b6d1a594e616f0e2f3f27d6d45fdf80aaa5da7a053726feca36a220a3046f87b2f92b90ec6fb5544

test:
  secret_key_base: 75ccb81eea9a5bbd814dbf208547298ca1ba6c6751a14cdb989ce853b9e3e9a1b57d4e0fe6c1cc9c7f4c97de58eacf1194a5ab9586a0624b562a231dd97a2024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
